# Generated by Django 2.2.3 on 2019-10-08 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Rendicion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.IntegerField()),
                ('tipo_de_gasto', models.CharField(max_length=50)),
                ('tipo_de_documento', models.CharField(choices=[('BO', 'BOLETA'), ('FA', 'FACTURA'), ('BE', 'BOLETA ELECTRÓNICA'), ('FE', 'FACTURA ELECTRÓNICA')], default='BO', max_length=2)),
                ('comentario', models.TextField(max_length=250)),
                ('comprobante', models.ImageField(upload_to='boletas/')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Centro')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Item')),
            ],
        ),
        migrations.CreateModel(
            name='RendicionEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rendicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Rendicion')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
