# Generated by Django 2.2.6 on 2019-10-09 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0002_auto_20191008_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='codigo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendicionestado',
            name='comentario',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rendicionestado',
            name='estado',
            field=models.CharField(choices=[('CR', 'Creado'), ('RV', 'Re Validar'), ('RE', 'Rechazado'), ('AP', 'Aprobado')], default='CR', max_length=2),
        ),
        migrations.CreateModel(
            name='CentroUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Centro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
